<?php
	$lang = array(

		//title
		"store" => "Geschäft",
		"cart" => "Warenkorb",
		"bill" => "Fakturierung",
		"profile" => "Profil",

		//header
		"products" => "Produkte",
		"logout" => "Ausloggen",
		"chooselang" => "Sprachauswahl",
		"sendmsg" => "Nachricht senden",
		"settings" => "Optionen",
		"adminsurf" => "Administrator Oberfläche",
		"login" => "Einloggen",
		"reg" => "Registrieren",
		"about" => "Über uns",

		//feedback.php
		"feed" => "Rückmeldungen",

		//alerts <script>
		"alert1" => "Sie haben erfolgreich hinzugefügt ",
		"alert2" => " Produkt!",
		"alert3" => "Falsche Kombination aus Benutzername und Kennwort!",
		"alert4" => "Sie haben dieses Produkt bereits hinzugefügt!",
		"alert5" => "Produkt erfolgreich entfernt!",
		"alert6" => "Fehler",
		"alert7" => "Sind Sie sicher, dass Sie löschen möchten ",
		"alert8" => " Produkt?",
		"alert9" => "Sind Sie sicher, dass Sie den Benutzer ",
		"alert10" => " löschen möchten?",
		"alert11" => "Falsche Kombination aus Benutzername und Kennwort!",
		"alert12" => "Dieser Benutzername ist bereits vergeben! Bitte geben Sie einen anderen ein!",
		"alert13" => "Die eingegebenen Passwörter stimmen nicht überein!",
		"alert14" => "Erfolgreich registriert! Sie können sich jetzt anmelden!",
		"alert15" => "Nachricht erfolgreich gesendet!",
		"alert16" => "Daten erfolgreich aktualisiert!",
		"alert17" => "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Dieser Vorgang kann später nicht mehr rückgängig gemacht werden!",
		"alert18" => "Vielen Dank für Ihr Feedback!",
		//about us
		"rate" => "Bewerten Sie unsere Website!",
		"15" => "Bewerten Sie es von 1 bis 5!",
		"youropinion" => "Deine Meinung...",
		"ratebtn" => "Auswertung",
		"sumrate" => "Alle Bewertungen:",
		"avrate" => "Durchschnittliche Bewertung:",
		"othersreview" => "Bewertungen von anderen:",
		"ratestar" => "Bewertung (Sterne)",
		"feedback" => "Meinung",
		"rate2" => "Auswertung.",

		//messages.php
		"msgs" => "Mitteilungen",
		"sender" => "Absender",
		"msg" => "Mitteilung",
		"date" => "Datum",
		"nomsg" => "Du hast keine Nachricht!",


		//deleteProducts.php
		"delprod" => "Produkte löschen",

		//addProduct.php
		"addprod" => "Produkt hinzufügen",
		"upload" => "hochladen",

		//adminProfile.php
		"logged" => "Sie haben sich als Administrator angemeldet",

		"deluser" => "Benutzer löschen",

		//payment.php
		"ordernum" => "Bestellnummer: ",
		"prodname" => "Produktname: ",
		"emailadd" => "E-Mail-Addresse: ",
		"phonenum" => "Telefonnummer: ",
		"deliverycountry" => "Lieferland: ",
		"streetaddress" => "Straße adresse: ",
		"city2" => "Stadt: ",
		"zip2" => "PLZ: ",
		"paymeth" => "Zahlungsmethode: ",
		"name2" => "Name: ",
		"payable" => "Zahlbar:",
		"down" => "Rechnung herunterladen",
		"download" => "Herunterladen",
		"pdate" => "Zeitpunkt des Kaufs",

		//settings.php
		"ppass" => "Kennwort...",
		"dataedit" => "Datenänderung",
		"edit" => "Bearbeiten",
		"adel" => "Konto löschen",
		"small" => "BEACHTUNG! Wenn Sie Ihr Konto löschen, können Sie es später nicht mehr rückgängig machen!",
		"del" => "Löschen",

		//checkout.php
		"piece" => "Stück",
		"next" => "Nächster",
		"shipping" => "Versanddetails",
		"fname" => "Vorname",
		"lname" => "Nachname",
		"phone" => "Telefonnummer",
		"delivery" => "Lieferland",
		"street" => "Straße adresse",
		"city" => "Stadt",
		"zip" => "PLZ",
		"billinginfo" => "Rechnungsadresse bei Unstimmigkeiten",
		"payment" => "Zahlung",
		"cod" => "Barzahlung bei Lieferung",
		"ap" => "Vorauszahlung",
		"cash" => "Kasse",
		"cod2" => "Sie müssen den Bestellbetrag an den Kurier übergeben.",
		"ap2" => "Bitte übertragen Sie den Kaufpreis auf die folgende Kontonummer: Kontonummer: 00000000-00000000 Name des Begünstigten: John Doe. Sobald der Betrag auf unserem Konto eingegangen ist, senden wir Ihre Bestellung.",
		"cash2" => "Sie können Ihre Bestellung persönlich abholen. Sie müssen lediglich unser Geschäft unter 06200000000 anrufen, einen Termin mit uns vereinbaren und Ihr Paket ist einsatzbereit. Adresse: 2836 Baj Apfelbaum utca 1.",

		//countries <option>
		"us" => "Vereinigte Staaten von Amerika",
		"ca" => "Kanada",
		"uk" => "Vereinigtes Königreich",
		"de" => "Deutschland",
		"hu" => "Ungarn",
		"af" => "Afghanistan",
		"al" => "Albanien",
		"dz" => "Algeria",
		"ad" => "Algerien",
		"ao" => "Angola",
		"ag" => "Antigua und Barbuda",
		"ar" => "Argentinien",
		"am" => "Armenien",
		"au" => "Australien",
		"at" => "Österreich",
		"az" => "Aserbaidschan",
		"bs" => "Bahamas",
		"bh" => "Bahrain",
		"bd" => "Bangladesch",
		"bb" => "Barbados",
		"by" => "Weißrussland",
		"be" => "Belgien",
		"bz" => "Belize",
		"bj" => "Bennin",
		"bt" => "Bhutan",
		"ba" => "Bosnien und Herzegowina",
		"bw" => "Botswana",
		"br" => "Brasilien",
		"bn" => "Brunei Darussalam",
		"bg" => "Bulgarien",
		"bf" => "Burkina Faso",
		"bi" => "Burundi",
		"cv" => "Cabo Verde",
		"kh" => "Kambodscha",
		"cm" => "Kamerun",
		"cf" => "Zentralafrikanische Republik",
		"td" => "Tschad",
		"cl" => "Chile",
		"cn" => "China",
		"co" => "Kolumbien",
		"km" => "Komoren",
		"cg" => "Kongo",
		"ck" => "Cookinseln",
		"cr" => "Costa Rica",
		"hr" => "Kroatien",
		"cu" => "Kuba",
		"cy" => "Zypern",
		"cz" => "Tschechien",
		"dk" => "Dänemark",
		"dj" => "Dschibuti",
		"dm" => "Dominica",
		"ec" => "Ecuador",
		"eg" => "Ägypten",
		"sv" => "El Salvador",
		"gq" => "Äquatorialguinea",
		"er" => "Eritrea",
		"ee" => "Estland",
		"sz" => "Eswatini",
		"et" => "Äthiopien",
		"fo" => "Färöer Inseln",
		"fj" => "Fidschi",
		"fi" => "Finnland",
		"fr" => "Frankreich",
		"ga" => "Gabun",
		"gm" => "Gambia",
		"ge" => "Georgia",
		"gh" => "Ghana",
		"gr" => "Griechenland",
		"gd" => "Grenada",
		"gt" => "Guatemala",
		"gn" => "Guinea",
		"gy" => "Guyana",
		"ht" => "Haiti",
		"hn" => "Honduras",
		"is" => "Island",
		"in" => "Indien",
		"id" => "Indonesia",
		"ir" => "Indonesien",
		"iq" => "Irak",
		"ie" => "Irland",
		"il" => "Israel",
		"it" => "Italien",
		"jm" => "Jamaika",
		"jp" => "Japan",
		"jo" => "Jordanien",
		"kz" => "Kasachstan",
		"ke" => "Kenia",
		"ki" => "Kiribati",
		"kw" => "Kuwait",
		"kg" => "Kirgisistan",
		"lv" => "Lettland",
		"lb" => "Libanon",
		"ls" => "Lesotho",
		"lr" => "Liberia",
		"ly" => "Libyen",
		"lt" => "Litauen",
		"lu" => "Luxemburg",
		"mg" => "Madagaskar",
		"mw" => "Malawi",
		"my" => "Malaysia",
		"mv" => "Malediven",
		"ml" => "Mali",
		"mt" => "Malta",
		"mh" => "Marshallinseln",
		"mr" => "Mauretanien",
		"mu" => "Mauritius",
		"mx" => "Mexiko",
		"fm" => "Mikronesien",
		"mc" => "Monaco",
		"mn" => "Mongolei",
		"me" => "Montenegro",
		"ma" => "Marokko",
		"mz" => "Mosambik",
		"mm" => "Myanmar",
		"na" => "Namibia",
		"nr" => "Nauru",
		"np" => "Nepal",
		"nl" => "Niederlande",
		"nz" => "Neuseeland",
		"ni" => "Nicaragua",
		"ne" => "Nigeria",
		"nu" => "Niue",
		"no" => "Norwegen",
		"om" => "Oman",
		"pk" => "Pakistan",
		"pw" => "Palau",
		"pa" => "Panama",
		"py" => "Paraguay",
		"pe" => "Peru",
		"ph" => "Philippinen",
		"pl" => "Polen",
		"pt" => "Portugal",
		"qa" => "Katar",
		"kr" => "Korea",
		"md" => "Moldawien",
		"ro" => "Rumänien",
		"ru" => "Russland",
		"rw" => "Ruanda",
		"kn" => "St. Kitts und Nevis",
		"lc" => "St. Lucia",
		"vc" => "St. Vincent und Grenadinen",
		"ws" => "Samoa",
		"sm" => "San Marino",
		"st" => "Sao Tome und Principe" ,
		"sa" => "Saudi-Arabien",
		"sn" => "Senegal",
		"rs" => "Serbien",
		"sc" => "Seychellen",
		"sl" => "Sierra Leone",
		"sg" => "Singapur",
		"sk" => "Slowakei",
		"si" => "Slowenien",
		"sb" => "Salomon-Inseln",
		"so" => "Somalia",
		"es" => "Spanien",
		"lk" => "Sri Lanka",
		"sd" => "Sudan",
		"sr" => "Suriname",
		"se" => "Schweden",
		"ch" => "Schweiz",
		"sy" => "Syrische Arabische Republik",
		"tj" => "Tadschikistan",
		"th" => "Thailand",
		"tl" => "Timor-Leste",
		"tg" => "Togo",
		"tk" => "Tokelau",
		"to" => "Tonga",
		"tt" => "Trinidad und Tobago",
		"tn" => "Tunesien",
		"tr" => "Türkei",
		"tv" => "Tuvalu",
		"ug" => "Uganda",
		"ua" => "Ukraine",
		"ae" => "Vereinigte Arabische Emirate",
		"tz" => "Tansania",
		"uy" => "Uruguay",
		"uz" => "Usbekistan",
		"ve" => "Venezuela",
		"vn" => "Vietnam",
		"ye" => "Jemen",
		"zm" => "Sambia",
		"zw" => "Zimbabwe",

		//adminLogin.php
		"adminlogin" => "Administrator einloggen",

		//registration.php
		"email" => "E-mail Adresse",
		"cpass" => "Kennwort bestätigen",
		"regalready" => "Bereits registriert? Hier können Sie sich einloggen!",

		//login.php
		"name" => "Name",
		"pass" => "Kennwort",
		"alert" => "WARNUNG! Die Feststelltaste ist aktiviert",
		"newhere" => "Sie haben noch keinen Account? Hier können Sie sich registrieren!",

		//sendmsg
		"yourmsg" => "Ihre Nachricht...",
		"send" => "Schicken",
		"small2" => "Die von Ihnen gesendete Nachricht wird vom Administrator zusammen mit Ihrem Benutzernamen und Ihrer E-Mail-Adresse angezeigt!",

		//cart.php
		"cartdetails" => "Warenkorb Details",
		"priceqty" => "Preis/Stück",
		"totalprice" => "Gesamtpreis",
		"total" => "Gesamtsumme",
		"remove" => "Entfernen",
		"empty" => "Ihr Warenkorb ist derzeit leer",
		"checkout" => "Weiter zur Kasse",

		//store.php
		"welcome" => "Willkommen",
		"appleprod" => "Apple Produkte",
		"image" => "Bild",
		"price" => "Preis",
		"qty" => "Menge",
		"addtocart" => "In den Warenkorb legen",

		//languages
		"eng" => "Englisch",
		"hun" => "Ungarische",
		"ger" => "Deutsche"
	);
?>