<?php
	$lang = array(

		//title
		"store" => "Store",
		"cart" => "Cart",
		"bill" => "Invoicing",
		"profile" => "Profile",

		//header
		"products" => "Products",
		"logout" => "Logout",
		"chooselang" => "Choose a language",
		"sendmsg" => "Send message",
		"settings" => "Settings",
		"adminsurf" => "Admin surface",
		"login" => "Login",
		"reg" => "Registration",
		"about" => "About us",

		//alerts <script>
		"alert1" => "You have successfully added ",
		"alert2" => " product!",
		"alert3" => "Incorrect username and password combination!",
		"alert4" => "You have already added this product!",
		"alert5" => "Product successfully removed!",
		"alert6" => "Error",
		"alert7" => "Are you sure you wanna delete ",
		"alert8" => " product?",
		"alert9" => "Are you sure you wanna delete user ",
		"alert10" => "?",
		"alert11" => "Incorrect username and password combination!",
		"alert12" => "This username is already taken! Please enter another one!",
		"alert13" => "The passwords you entered don't match!",
		"alert14" => "Successfully registered! You can now log in!",
		"alert15" => "Message sent successfully!",
		"alert16" => "Data updated successfully!",
		"alert17" => "Are you sure you wanna delete your account? This operation cannot be undone later!",
		"alert18" => "Thanks for your feedback!",

		//feedback.php
		"feed" => "Feedbacks",

		//about us
		"rate" => "Rate our webpage!",
		"15" => "Rate it from 1 to 5!",
		"youropinion" => "Your opinoin...",
		"ratebtn" => "Rate",
		"sumrate" => "All ratings:",
		"avrate" => "Average ratings:",
		"othersreview" => "Reviews by others:",
		"ratestar" => "Rates (stars)",
		"feedback" => "Feedback",
		"rate2" => "rates.",

		//messages.php
		"msgs" => "Messages",
		"sender" => "Sender",
		"msg" => "Message",
		"date" => "Date",
		"nomsg" => "You don't have any message!",

		//deleteProducts.php
		"delprod" => "Delete products",

		//addProduct.php
		"addprod" => "Add product",
		"upload" => "Upload",

		//adminProfile.php
		"logged" => "You logged in as Admin",

		"deluser" => "Delete users",

		//settings.php
		"ppass" => "Password...",
		"dataedit" => "Data modification",
		"edit" => "Edit",
		"adel" => "Delete account",
		"small" => "ATTENTION! If you delete your account, you will not be able to undo it later!",
		"del" => "Delete",

		//payment.php
		"ordernum" => "Order number: ",
		"prodname" => "Product(s) name: ",
		"emailadd" => "E-mail address: ",
		"phonenum" => "Phone number: ",
		"deliverycountry" => "Country of delivery: ",
		"streetaddress" => "Street address: ",
		"city2" => "City: ",
		"zip2" => "ZIP code: ",
		"paymeth" => "Payment method: ",
		"name2" => "Name: ",
		"payable" => "Payable:",
		"down" => "Download bill",
		"download" => "Download",
		"pdate" => "Date of purchase",

		//checkout.php
		"piece" => "piece",
		"next" => "Next",
		"shipping" => "Shipping details",
		"fname" => "First name",
		"lname" => "Last name",
		"phone" => "Phone number",
		"delivery" => "Country of delivery",
		"street" => "Street address",
		"city" => "City",
		"zip" => "ZIP code",
		"billinginfo" => "Billing address in case of discrepancy",
		"payment" => "Payment method",
		"cod" => "Cash on delivery",
		"ap" => "Advance payment",
		"cash" => "Cash",
		"cod2" => "You must hand over the amount of the order to the courier.",
		"ap2" => "Please transfer the purchase price to the following account number: Account number: 00000000-00000000 Beneficiary name: John Doe. As soon as the amount has arrived in our account, we will send your order.",
		"cash2" => "You can pick up your order in person. All you have to do is call our store on 06200000000, arrange an appointment with us and your package is ready to go. Address: 2836 Baj Appletree utca 1.",

		//countries <option>
		"us" => "United States of America",
		"ca" => "Canada",
		"uk" => "United Kingdom",
		"de" => "Germany",
		"hu" => "Hungary",
		"af" => "Afghanistan",
		"al" => "Albania",
		"dz" => "Algeria",
		"ad" => "Andorra",
		"ao" => "Angola",
		"ag" => "Antigua and Barbuda",
		"ar" => "Argentina",
		"am" => "Armenia",
		"au" => "Australia",
		"at" => "Austria",
		"az" => "Azerbaijan",
		"bs" => "Bahamas",
		"bh" => "Bahrain",
		"bd" => "Bangladesh",
		"bb" => "Barbados",
		"by" => "Belorus",
		"be" => "Belgium",
		"bz" => "Belize",
		"bj" => "Bennin",
		"bt" => "Bhutan",
		"ba" => "Bosnia and Herzegovina",
		"bw" => "Botswana",
		"br" => "Brazil",
		"bn" => "Brunei Darussalam",
		"bg" => "Bulgaria",
		"bf" => "Burkina Faso",
		"bi" => "Burundi",
		"cv" => "Cabo Verde",
		"kh" => "Cambodia",
		"cm" => "Cameroon",
		"cf" => "Central African Republic",
		"td" => "Chad",
		"cl" => "Chile",
		"cn" => "China",
		"co" => "Colombia",
		"km" => "Comoros",
		"cg" => "Congo",
		"ck" => "Cook Islands",
		"cr" => "Costa Rica",
		"hr" => "Croatia",
		"cu" => "Cuba",
		"cy" => "Cyprus",
		"cz" => "Czech Republic",
		"dk" => "Denmark",
		"dj" => "Djibouti",
		"dm" => "Dominica",
		"ec" => "Ecuador",
		"eg" => "Egypt",
		"sv" => "El Salvador",
		"gq" => "Equatorial Guinea",
		"er" => "Eritrea",
		"ee" => "Estonia",
		"sz" => "Eswatini",
		"et" => "Ethiopia",
		"fo" => "Faroe Islands",
		"fj" => "Fiji",
		"fi" => "Finland",
		"fr" => "France",
		"ga" => "Gabon",
		"gm" => "Gambia",
		"ge" => "Georgia",
		"gh" => "Ghana",
		"gr" => "Greece",
		"gd" => "Grenada",
		"gt" => "Guatemala",
		"gn" => "Guinea",
		"gy" => "Guyana",
		"ht" => "Haiti",
		"hn" => "Honduras",
		"is" => "Iceland",
		"in" => "India",
		"id" => "Indonesia",
		"ir" => "Iran",
		"iq" => "Iraq",
		"ie" => "Ireland",
		"il" => "Israel",
		"it" => "Italy",
		"jm" => "Jamaica",
		"jp" => "Japan",
		"jo" => "Jordan",
		"kz" => "Kazakhstan",
		"ke" => "Kenya",
		"ki" => "Kiribati",
		"kw" => "Kuwait",
		"kg" => "kyrgyzstan",
		"lv" => "Latvia",
		"lb" => "Lebanon",
		"ls" => "Lesotho",
		"lr" => "Liberia",
		"ly" => "Libya",
		"lt" => "Lithuania",
		"lu" => "Luxembourg",
		"mg" => "Madagascar",
		"mw" => "Malawi",
		"my" => "Malaysia",
		"mv" => "Maldives",
		"ml" => "Mali",
		"mt" => "Malta",
		"mh" => "Marshall Islands",
		"mr" => "Mauritania",
		"mu" => "Mauritius",
		"mx" => "Mexico",
		"fm" => "Micronesia",
		"mc" => "Monaco",
		"mn" => "Mongolia",
		"me" => "Montenegro",
		"ma" => "Morocco",
		"mz" => "Mozambique",
		"mm" => "Myanmar",
		"na" => "Namibia",
		"nr" => "Nauru",
		"np" => "Nepal",
		"nl" => "Netherlands",
		"nz" => "New Zealand",
		"ni" => "Nicaragua",
		"ne" => "Nigeria",
		"nu" => "Niue",
		"no" => "Norway",
		"om" => "Oman",
		"pk" => "Pakistan",
		"pw" => "Palau",
		"pa" => "Panama",
		"py" => "Paraguay",
		"pe" => "Peru",
		"ph" => "Phillippines",
		"pl" => "Poland",
		"pt" => "Portugal",
		"qa" => "Qatar",
		"kr" => "Korea",
		"md" => "Moldova",
		"ro" => "Romania",
		"ru" => "Russia",
		"rw" => "Rwanda",
		"kn" => "Saint Kitts and Nevis",
		"lc" => "Saint Lucia",
		"vc" => "Saint Vincent and Grenadines",
		"ws" => "Samoa",
		"sm" => "San Marino",
		"st" => "Sao Tome and Principe" ,
		"sa" => "Saudi Arabia",
		"sn" => "Senegal",
		"rs" => "Serbia",
		"sc" => "Seychelles",
		"sl" => "Sierra Leone",
		"sg" => "Singapore",
		"sk" => "Slovakia",
		"si" => "Slovenia",
		"sb" => "Solomon Islands",
		"so" => "Somalia",
		"es" => "Spain",
		"lk" => "Sri Lanka",
		"sd" => "Sudan",
		"sr" => "Suriname",
		"se" => "Sweden",
		"ch" => "Switzerland",
		"sy" => "Syrian Arab Republic",
		"tj" => "Tajikistan",
		"th" => "Thailand",
		"tl" => "Timor-Leste",
		"tg" => "Togo",
		"tk" => "Tokelau",
		"to" => "Tonga",
		"tt" => "Trinidad and Tobago",
		"tn" => "Tunisia",
		"tr" => "Turkey",
		"tv" => "Tuvalu",
		"ug" => "Uganda",
		"ua" => "Ukraine",
		"ae" => "United Arab emirates",
		"tz" => "Tanzania",
		"uy" => "Uruguay",
		"uz" => "Uzbekistan",
		"ve" => "Venezuela",
		"vn" => "Viet Nam",
		"ye" => "Yemen",
		"zm" => "Zambia",
		"zw" => "Zimbabwe",

		//adminLogin.php
		"adminlogin" => "Admin login",

		//registration.php
		"email" => "E-mail address",
		"cpass" => "Confirm password",
		"regalready" => "Already registered? You can log in here!",

		//login.php
		"name" => "Name",
		"pass" => "Password",
		"alert" => "WARNING! Caps Lock in on.",
		"newhere" => "Don't have an account yet? You can register here!",

		//sendmsg
		"yourmsg" => "Your message...",
		"send" => "Send",
		"small2" => "The message you have sent will be seen by the administrator along with your username and email address!",

		//cart.php
		"cartdetails" => "Cart details",
		"priceqty" => "Price/quantity",
		"totalprice" => "Total price",
		"total" => "Total",
		"remove" => "Remove",
		"empty" => "Your cart is currently empty",
		"checkout" => "Continue to checkout",

		//store.php
		"welcome" => "Welcome",
		"appleprod" => "Apple products",
		"image" => "Image",
		"price" => "Price",
		"qty" => "Quantity",
		"addtocart" => "Add to cart",

		//languages
		"eng" => "English",
		"hun" => "Hungarian",
		"ger" => "German"
	);
?>