<?php
	$lang = array(

		//title
		"store" => "Áruház",
		"cart" => "Kosár",
		"bill" => "Számlázás",

		//header
		"products" => "Termékek",
		"logout" => "Kilépés",
		"chooselang" => "Válasszon nyelvet",
		"sendmsg" => "Üzenet küldése",
		"settings" => "Beállítások",
		"adminsurf" => "Admin felület",
		"login" => "Belépés",
		"reg" => "Regisztráció",
		"about" => "Rólunk",

		//settings.php
		"ppass" => "Jelszó...",
		"dataedit" => "Adatok módosítása",
		"edit" => "Módosítás",
		"adel" => "Fiók törlése",
		"small" => "FIGYELEM! Ha törli a fiókját, később már nem lehet ezt a műveletet visszavonni!",
		"del" => "Törlés",

		//payment.php
		"ordernum" => "Rendelés száma: ",
		"prodname" => "Termék(ek) neve: ",
		"emailadd" => "E-mail cím: ",
		"phonenum" => "Telefonszám: ",
		"deliverycountry" => "Szállítási ország: ",
		"streetaddress" => "Utca házszám: ",
		"city2" => "Város: ",
		"zip2" => "Irányítószám: ",
		"paymeth" => "Fizetési mód: ",
		"name2" => "Név: ",
		"payable" => "Fizetendő:",
		"down" => "Számla letöltése",
		"download" => "Letöltés",

		//checkout.php
		"piece" => "darab",
		"next" => "Tovább",
		"shipping" => "Szállítási adatok",
		"fname" => "Keresztnév",
		"lname" => "Vezetéknév",
		"phone" => "Telefonszám",
		"delivery" => "Szállítási ország",
		"street" => "Utca házszám",
		"city" => "Város",
		"zip" => "Irányítószám",
		"billinginfo" => "Számlázási cím eltérés esetén",
		"payment" => "Fizetési mód",
		"cod" => "Utánvét",
		"ap" => "Előre utalás",
		"cash" => "Készpénz",
		"cod2" => "A megrendelés összegét a futárnak kell átadnod.",
		"ap2" => "Kérjük utald át a vételárat a következő számlaszámra: Számlaszám: 00000000-00000000 kedvezményezett neve: John Doe. Amint megérkezett az összeg a számlánkra, megküldjük rendelésedet.",
		"cash2" => "Személyesen tudod átvenni megrendelésedet. Nincs más dolgod mint felhívni áruházunkat a 06200000000 -as telefonszámon, egyeztetsz velünk egy időpontot és már készen is áll a csomagod az elvitelre. Cím: 2836 Baj Almafa utca 1.",

		//countries <option>
		"us" => "Amerikai Egyesült Államok",
		"ca" => "Kanada",
		"uk" => "Egyesült Királyság",
		"de" => "Németország",
		"hu" => "Magyarország",
		"af" => "Afganisztán",
		"al" => "Albánia",
		"dz" => "Algéria",
		"ad" => "Andorra",
		"ao" => "Angola",
		"ag" => "Antigua és Barbuda",
		"ar" => "Aregentína",
		"am" => "Örményország",
		"au" => "Ausztrália",
		"at" => "Ausztria",
		"az" => "Azerbajdzsán",
		"bs" => "Bahama-szigetek",
		"bh" => "Bahrein",
		"bd" => "Banglades",
		"bb" => "Barbados",
		"by" => "Belorusz",
		"be" => "Belgium",
		"bz" => "Belize",
		"bj" => "Bennin",
		"bt" => "Bolívia",
		"ba" => "Bosznia és Hercegovina",
		"bw" => "Botswana",
		"br" => "Brazília",
		"bn" => "Brunei Darussalam",
		"bg" => "Bulgária",
		"bf" => "Burkina Faso",
		"bi" => "Burundi",
		"cv" => "Cabo Verde",
		"kh" => "Kambodzsa",
		"cm" => "Kameron",
		"cf" => "Közép-Afrikai Köztársaság",
		"td" => "Csád",
		"cl" => "Csíle",
		"cn" => "Kína",
		"co" => "Kolumbia",
		"km" => "Komorok",
		"cg" => "Kongó",
		"ck" => "Cook-szigetek",
		"cr" => "Koszta Rika",
		"hr" => "Horvátország",
		"cu" => "Kuba",
		"cy" => "Ciprus",
		"cz" => "Csehország",
		"dk" => "Dánia",
		"dj" => "Dzsibuti",
		"dm" => "Dominika",
		"ec" => "Ecuador",
		"eg" => "Egyiptom",
		"sv" => "El Salvador",
		"gq" => "Egyenlítői-Guinea",
		"er" => "Eritrea",
		"ee" => "Észtország",
		"sz" => "Eswatini",
		"et" => "Etiópia",
		"fo" => "Faroe Szigetek",
		"fj" => "Fidzsi",
		"fi" => "Finnország",
		"fr" => "Franciaorzság",
		"ga" => "Gabon",
		"gm" => "Gambia",
		"ge" => "Grúzia",
		"gh" => "Ghána",
		"gr" => "Görögország",
		"gd" => "Grenada",
		"gt" => "Guatemala",
		"gn" => "Guinea",
		"gy" => "Guyana",
		"ht" => "Haiti",
		"hn" => "Honduras",
		"is" => "Izland",
		"in" => "India",
		"id" => "Indonézia",
		"ir" => "Irán",
		"iq" => "Irak",
		"ie" => "Írország",
		"il" => "Izrael",
		"it" => "Olaszország",
		"jm" => "Jamaika",
		"jp" => "Japán",
		"jo" => "Jordánia",
		"kz" => "kazahsztán",
		"ke" => "Kenya",
		"ki" => "Kiribati",
		"kw" => "Kuvait",
		"kg" => "kirgizisztán",
		"lv" => "Lettország",
		"lb" => "Libanon",
		"ls" => "Lesotho",
		"lr" => "Libéria",
		"ly" => "Líbia",
		"lt" => "Litvánia",
		"lu" => "Luxemburg",
		"mg" => "Madagaszkár",
		"mw" => "Malawi",
		"my" => "Malaysia",
		"mv" => "Maldív-szigetek",
		"ml" => "Mali",
		"mt" => "Málta",
		"mh" => "Marshall-szigetek",
		"mr" => "Mauritánia",
		"mu" => "Mauritius",
		"mx" => "Mexikó",
		"fm" => "Mikronézia",
		"mc" => "Monaco",
		"mn" => "Mongólia",
		"me" => "Montenegró",
		"ma" => "Morokkó",
		"mz" => "Mozambik",
		"mm" => "Mianmar",
		"na" => "Namíbia",
		"nr" => "Nauru",
		"np" => "Nepál",
		"nl" => "Hollandia",
		"nz" => "Új Zéland",
		"ni" => "Nicaragua",
		"ne" => "Nigéria",
		"nu" => "Niue",
		"no" => "Norvégia",
		"om" => "Omán",
		"pk" => "Pakisztán",
		"pw" => "Palau",
		"pa" => "Panama",
		"py" => "Paraguay",
		"pe" => "Peru",
		"ph" => "Fülöp-szigetek",
		"pl" => "Lengyelország",
		"pt" => "Portugália",
		"qa" => "Katar",
		"kr" => "Kórea",
		"md" => "Moldova",
		"ro" => "Románia",
		"ru" => "Oroszország",
		"rw" => "Ruanda",
		"kn" => "Saint Kitts és Nevis",
		"lc" => "Szent Lucia",
		"vc" => "Szent Vincent és a Grenadinek",
		"ws" => "Szamoa",
		"sm" => "San Marino",
		"st" => "sao Tomé és Principe" ,
		"sa" => "Saudi Arábia",
		"sn" => "Szenegál",
		"rs" => "Szerbia",
		"sc" => "Seychelle-szigetek",
		"sl" => "Sierra Leone",
		"sg" => "Szingapur",
		"sk" => "Szlovákia",
		"si" => "Szlovénia",
		"sb" => "Salamon-szigetek",
		"so" => "Szomália",
		"es" => "Spanyolország",
		"lk" => "Srí Lanka",
		"sd" => "Szudán",
		"sr" => "Suriname",
		"se" => "Svédország",
		"ch" => "Svájc",
		"sy" => "Szíriai Arab Köztársaság",
		"tj" => "Tádzsikisztán",
		"th" => "Tájföld",
		"tl" => "Timor-Leste",
		"tg" => "Togo",
		"tk" => "Tokelau",
		"to" => "Tonga",
		"tt" => "Trinidad és Tobago",
		"tn" => "Tunézia",
		"tr" => "Törökország",
		"tv" => "Tuvalu",
		"ug" => "Uganda",
		"ua" => "Ukrajna",
		"ae" => "Egyesült Arab Emírségek",
		"tz" => "Tanzánia",
		"uy" => "Uruguay",
		"uz" => "Üzbegisztán",
		"ve" => "Venezuela",
		"vn" => "Vietnám",
		"ye" => "Jemen",
		"zm" => "Zambia",
		"zw" => "Zimbabwe",

		//adminLogin.php
		"adminlogin" => "Admin belépés",

		//registration.php
		"email" => "E-mail cím",
		"cpass" => "Jelszó mégegyszer",
		"regalready" => "Regisztrált már? Itt bejelentkezhet!",
 

		//login.php
		"name" => "Név",
		"pass" => "Jelszó",
		"alert" => "Figyelem! A Caps lock be van kapcsolva.",
		"newhere" => "Nincs még fiókja? Itt regisztrálhat!",


		//sendmsg.php
		"yourmsg" => "Üzenete...",
		"send" => "Küldés",
		"small2" => "Az ön által küldött üzenetet az admininsztrátor látni fogja a felhasználónevével és e-mail címével együtt!",

		//cart.php
		"cartdetails" => "Kosár részletei",
		"priceqty" => "Ár/darab",
		"totalprice" => "Teljes ár",
		"total" => "Végösszeg",
		"remove" => "Eltávolítás",
		"empty" => "Kosara jelenleg üres",
		"checkout" => "Tovább",

		//store.php
		"welcome" => "Üdvözöljük",
		"appleprod" => "Apple termékek",
		"image" => "Kép",
		"price" => "Ár",
		"qty" => "Mennyiség",
		"addtocart" => "Kosárba helyezés",

		//languages
		"eng" => "Angol",
		"hun" => "Magyar",
		"ger" => "Német"
	);
?>